name: download.versatiles.org

services:
  server:
    build:
      dockerfile: ./Dockerfile
      target: $TARGET
    volumes:
      - nginx_conf:/volumes/nginx_conf/
      - remote_files:/volumes/remote_files
      - local_files:/volumes/local_files
      - logs:/volumes/logs
    networks:
      - server

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/Berlin
      - URL=$DOMAIN
      #- SUBDOMAINS=download
      #- ONLY_SUBDOMAINS=true
      - VALIDATION=http
      #- CERTPROVIDER=
      #- DNSPLUGIN=cloudflare
      #- PROPAGATION=
      #- EMAIL=
      #- EXTRA_DOMAINS=
      - STAGING=false
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - nginx_conf:/config/nginx/
      - remote_files:/usr/share/www/remote_files
      - local_files:/usr/share/www/local_files
      - logs:/var/log/
    networks:
      - server
networks:
  server:
    driver: bridge
volumes:
  remote_files: { driver: local, driver_opts: { type: 'none', o: 'bind', device: './volumes/remote_files' } }
  local_files: { driver: local, driver_opts: { type: 'none', o: 'bind', device: './volumes/local_files' } }
  nginx_conf: { driver: local, driver_opts: { type: 'none', o: 'bind', device: './volumes/nginx_conf' } }
  logs: { driver: local, driver_opts: { type: 'none', o: 'bind', device: './volumes/logs' } }
