name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '!**' # Don't run twice on commits with tags
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  release:
    name: Lint, test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Sync SvelteKit
        run: npx svelte-kit sync

      - name: Check vulnerabilities
        run: npm audit --audit-level=high

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Tests
        run: npm run test

      - name: Build site
        run: npx tsx src/generate_testdata.ts && npm run build:site

      - name: Generate test coverage
        run: npm run test-coverage

      - name: Upload test coverage
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
