name: Build and deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "!**" # Don't run twice on commits with tags
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  release:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build and deploy
        run: npm start
        env:
          BUNNY: ${{ secrets.BUNNY }}
